import "../styles.css";
// `bones/registry.ts` is auto-generated by boneyard's Vite plugin / CLI. It
// opens with a `"use client"` directive that boneyard emits for Next.js — in
// our Vite app it's a no-op string expression and can be ignored.
import "../bones/registry";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter } from "react-router-dom";
import { configureBoneyard } from "boneyard-js/react";
import { PrintApp } from "./App";
import { ErrorBoundary } from "../ErrorBoundary";

// Global Skeleton defaults — must mirror `boneyard.config.json` (which the
// capture CLI reads but the runtime does not). Kept here, not in registry.ts,
// because the Vite HMR plugin rewrites registry.ts without preserving any
// configureBoneyard call.
// U-2 (#255): skeletons are `paper-sunk` shimmer on the warm paper field, NOT
// the dark near-black blocks the dark era used (the milestone retired those).
// boneyard's `color` is a plain CSS string applied before any element exists,
// so a `var(--…)` may not resolve here — use the oklch literal matching
// `--color-paper-sunk`. Detector-window skeletons override this per-component
// with a `frame-edge` fill (the window is dark even while loading). `darkColor`
// mirrors `color` — there is no dark mode, so it only guards against a stray
// dark fallback.
configureBoneyard({
  color: "oklch(0.951 0.008 84)",
  darkColor: "oklch(0.951 0.008 84)",
  animate: "pulse",
  boneClass: "bone",
});

const queryClient = new QueryClient({
  defaultOptions: {
    queries: { staleTime: 30_000, retry: 1, refetchOnWindowFocus: false },
  },
});

const root = document.getElementById("app");
if (!root) throw new Error("#app root missing");
createRoot(root).render(
  <StrictMode>
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <BrowserRouter>
          <PrintApp />
        </BrowserRouter>
      </QueryClientProvider>
    </ErrorBoundary>
  </StrictMode>,
);
