"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _plot_card from './plot-card.bones.json'

configureBoneyard({"color":"rgba(30, 31, 38, 1)","darkColor":"rgba(42, 44, 52, 1)","animate":"pulse","boneClass":"bone"})

registerBones({
  "plot-card": _plot_card,
})
