using Test

const _TEST_TIMES = Dict{String,Float64}()
_timed_include(f) = (_TEST_TIMES[f] = @elapsed include(f))

@testset "HimalayaUI" begin
    _timed_include("test_config.jl")
    _timed_include("test_db.jl")
    _timed_include("test_migrate_comparisons_to_series.jl")
    _timed_include("test_datfile.jl")
    _timed_include("test_manifest.jl")
    _timed_include("test_hash.jl")
    _timed_include("test_hash_peak_set_memoization.jl")
    _timed_include("test_pipeline.jl")
    _timed_include("test_auto_group_peak_id_claiming.jl")
    _timed_include("test_effective_peaks_sharpness_passthrough.jl")
    _timed_include("test_fast_skip.jl")
    _timed_include("test_json.jl")
    _timed_include("test_http.jl")
    _timed_include("test_routes_health.jl")
    _timed_include("test_routes_users.jl")
    _timed_include("test_routes_experiments.jl")
    _timed_include("test_routes_samples.jl")
    _timed_include("test_routes_exposures.jl")
    _timed_include("test_image.jl")
    _timed_include("test_routes_image.jl")
    _timed_include("test_routes_status.jl")
    _timed_include("test_routes_peaks.jl")
    _timed_include("test_routes_messages.jl")
    _timed_include("test_routes_trace.jl")
    _timed_include("test_routes_analysis.jl")
    _timed_include("test_speculative.jl")
    _timed_include("test_routes_export.jl")
    _timed_include("test_routes_mentions.jl")
    _timed_include("test_actions.jl")
    _timed_include("test_events.jl")
    _timed_include("test_assignments.jl")
    _timed_include("test_assignment_reattach.jl")
    _timed_include("test_sse.jl")
    _timed_include("test_routes_sse_broadcast.jl")
    _timed_include("test_route_response_shapes.jl")
    _timed_include("test_route_validation_routing.jl")
    _timed_include("test_idempotency.jl")
    _timed_include("test_idempotency_replay_invariant.jl")
    _timed_include("test_concurrent_writes.jl")
    _timed_include("test_idempotency_sse_suppression.jl")
    _timed_include("test_comparisons.jl")
    _timed_include("test_routes_series.jl")
    _timed_include("test_picker_routes.jl")
    _timed_include("test_picker_samples_route.jl")
    _timed_include("test_routes_resolve.jl")
    _timed_include("test_comparison_pins.jl")
    _timed_include("test_validate.jl")
    _timed_include("test_migrate_toml.jl")
    _timed_include("test_spa_fallback.jl")
end

# Print slowest-first; harmless under Pkg.test, informative for M3 balancing.
let rows = sort(collect(_TEST_TIMES); by = last, rev = true)
    println("\n── per-file test timing (slowest first) ──")
    for (f, t) in rows
        println(rpad(f, 42), lpad(round(t; digits=1), 8), " s")
    end
end
